version: '3.3'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'kwetter_docker_db'
      MYSQL_USER: 'Kwetter'
      MYSQL_PASSWORD: 'kwetter'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - kwetternet

  kwetter_backend:
    image: ronindebeek/kwetter_backend:development
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - kwetternet
      
  kwetter_angular:
    image: ronindebeek/kwetter_angular:development
    ports:
      - 4200:4200

networks:
  kwetternet:
    driver: bridge