version: '3.3'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - kwetternet

  kwetter_backend:
    image: ronindebeek/kwetter_backend:release
    environment:
      SPRING_PROFILE:
      DATABASE_HOST:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      DATABASE_DRIVER:
      MAIL_HOST:
      MAIL_PORT:
      MAIL_USERNAME:
      MAIL_PASSWORD:
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - kwetternet
      
  kwetter_angular:
    image: ronindebeek/kwetter_angular:release
    ports:
      - 4200:4200

networks:
  kwetternet:
    driver: bridge
    