version: '3.3'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - kwetternet

  kwetter_backend:
    image: ronindebeek/kwetter_backend:development-latest
    environment:
      SPRING_PROFILE:
      FRONTEND_HOST_LOCATION:
      WAIT_HOSTS:
      DATABASE_HOST:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      DATABASE_DRIVER:
      MAIL_HOST:
      MAIL_PORT:
      MAIL_USERNAME:
      MAIL_PASSWORD:
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - kwetternet

  kwetter_angular:
    image: ronindebeek/kwetter_angular:development-latest
    ports:
      - 4200:4200
    expose:
      - 3306      
    networks:
      - kwetternet

  ngrok_angular:
    image: gtriggiano/ngrok-tunnel
    environment:
        TARGET_HOST: 'kwetter_angular'
        TARGET_PORT: 4200
        NGROK_REGION: 'eu'
    ports:
        - 4040:4040
    networks:
      - kwetternet

  ngrok_backend:
    image: gtriggiano/ngrok-tunnel
    environment:
        TARGET_HOST: 'kwetter_backend'
        TARGET_PORT: 8080
        NGROK_REGION: 'eu'
    ports:
        - 4041:4040
    networks:
      - kwetternet

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300

networks:
  kwetternet:
    driver: bridge
